spring:
  main:
    web-environment: false
ena:
  processor_list: ENAStudyProcessor,ENAExperimentProcessor
  login_name: ${enaLoginName}
  password: ${enaPassword}
  submission:
    url: https://www-test.ebi.ac.uk/ena/submit/drop-box/submit