server:
  port: 0
spring:
  boot:
    admin:
      url: http://localhost:9000

ena:
  processor_list: ENAStudyProcessor,ENAExperimentProcessor
  login_name: ${enaLoginName}
  password: ${enaPassword}
  submission:
    url: https://www-test.ebi.ac.uk/ena/submit/drop-box/submit
  action_services: StudyActionService,SampleActionService,AssayActionService,AssayDataActionService,ValidationActionService,SequenceVariationAnalysisActionService
