usi:
  archive:
    dispatcher:
      enabled: BioSamples,BioStudies,Ena
      data-types:
        BioSamples:
          - samples
        BioStudies:
          - projects
        Ena:
          - enaStudies
          - sequencingExperiments
          - sequencingRuns
    repositoryMapping:
      analysis:
        - variantCalls
      assayData:
        - sequencingRuns
        - metabolightsAssayData
      assay:
        - sequencingExperiments
        - metabolomicsAssays
      egaDacPolicy:
        - egaDacPolicies
      egaDac:
        - egaDacs
      egaDataset:
        - egaDatasets
      project:
        - projects
      protocol:
        - metabolightsProtocols
      sampleGroup:
      sample:
        - samples
      study:
        - enaStudies
        - metabolomicsStudies

spring:
  application:
    name: ena-validator

server:
  port: 0

ena:
  processor_list: ENAStudyProcessor,ENAExperimentProcessor
  login_name: ${enaLoginName}
  password: ${enaPassword}
  submission:
    url: https://www-test.ebi.ac.uk/ena/submit/drop-box/submit
  action_services: StudyActionService,SampleActionService,AssayActionService,AssayDataActionService,ValidationActionService,SequenceVariationAnalysisActionService

